=== sin90lzc/my_mavens/train_xml/src/main/resources/school_opt.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sin90lzc.com/school" xmlns:s="http://www.sin90lzc.com/school"
	xmlns="http://www.sin90lzc.com/school" elementFormDefault="qualified">

	<xs:simpleType name="subject3">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Math"></xs:enumeration>
					<xs:enumeration value="Chinese"></xs:enumeration>
					<xs:enumeration value="English"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="数学|语文|英语"></xs:pattern>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

	<xs:complexType name="subjectType">
		<xs:simpleContent>
			<xs:extension base="subject3">
				<xs:attribute name="main" default="false" type="xs:boolean"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z](\w*)"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="name" type="nameType"></xs:element>

	<xs:complexType name="teacherType">
		<xs:sequence>
			<xs:element ref="name"></xs:element>
			<xs:element name="subject" type="subjectType"></xs:element>
		</xs:sequence>
		<xs:attribute name="head" type="xs:boolean"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="teachersType">
		<xs:sequence>
			<xs:element name="teacher" minOccurs="1" maxOccurs="unbounded"
				type="teacherType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="refTeacherType">
		<xs:attribute name="ref" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element ref="name"></xs:element>
			<xs:element name="teacher" type="refTeacherType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="studentsType">
		<xs:sequence>
			<xs:element name="student" maxOccurs="unbounded"
				minOccurs="1" type="studentType">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="schoolType">
		<xs:sequence>
			<xs:element name="teachers" type="teachersType">
				<xs:unique name="uni_tname">
					<xs:selector xpath="./s:teacher"></xs:selector>
					<xs:field xpath="./s:name"></xs:field>
				</xs:unique>
				<xs:unique name="uni_head">
					<xs:selector xpath="./s:teacher"></xs:selector>
					<xs:field xpath="./@head"></xs:field>
				</xs:unique>
			</xs:element>
			<xs:element name="students" type="studentsType">
				<xs:unique name="uni_sname">
					<xs:selector xpath="./s:student"></xs:selector>
					<xs:field xpath="./s:name"></xs:field>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="school" type="schoolType">
		<xs:key name="key_tname">
			<xs:selector xpath="./s:teachers/s:teacher"></xs:selector>
			<xs:field xpath="./s:name"></xs:field>
		</xs:key>
		<xs:keyref name="ref_tname" refer="key_tname">
			<xs:selector xpath="./s:students/s:student"></xs:selector>
			<xs:field xpath="./s:teacher/@ref"></xs:field>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== sin90lzc/my_mavens/train_xml/src/main/resources/school.xml
<?xml version="1.0" encoding="utf-8" ?>
<school xmlns="http://www.sin90lzc.com/school" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sin90lzc.com/school school_opt.xsd">
	<teachers>
		<teacher head="true">
			<name>Tim</name>
			<subject main="true">Math</subject>
		</teacher>
		<teacher>
			<name>Rain</name>
			<subject>英语</subject>
		</teacher>
		<teacher>
			<name>Petter</name>
			<subject>语文</subject>
		</teacher>
	</teachers>
	<students>
		<student>
			<name>Sally</name>
			<teacher ref="Tim" />
		</student>
		<student>
			<name>Edison</name>
			<teacher ref="Petter" />
		</student>
	</students>
</school>
